spring:
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    driver-class-name: org.postgresql.Driver
    username: analyzer
    password: analyzer
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

kafka:
  bootstrap-servers: localhost:9092
  topics:
    hubs: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1
  consumers:
    snapshots:
      group-id: analyzer-snapshots
      poll-timeout: 1000
    hubs:
      group-id: analyzer-hubs
      poll-timeout: 1000

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
